####################################################################
# Hachyderm Prometheus Config (/etc/prometheus/prometheus.yml)
#
# DO NOT EDIT THIS FILE MANUALLY - IT IS AUTOGENERATED PERIODCALLY
# BY A SYSTEMD TIMER BASED ON TAGS IN TAILSCALE!
#
# Last rendered: {{ time.Now.Format "2006-01-02 15:04:05" }}
####################################################################

global:
  scrape_interval: 30s
  evaluation_interval: 1m

alerting:
  alertmanagers:
    - static_configs:
      - targets:
        # - alertmanager:9093

# Load rules once and periodically evaluate them
rule_files:
  # - "rules.yml"


scrape_configs:
###############################################################################
# SELF - PROMETHEUS
###############################################################################
  # first we scrape ourselves
  - job_name: "prometheus"
    static_configs:
      - targets: ["prod-prometheus01:9090"]

###############################################################################
# SYNTHETICS - BLACKBOX EXPORTER
###############################################################################
  # do some blackbox probing to make sure we know when services are up and stuff
  - job_name: "blackbox"
    metrics_path: /probe
    params:
      module: [http_2xx_get]
    static_configs:
      - targets:
        - https://hachyderm.io
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: localhost:9115

###############################################################################
# NODE EXPORTER (ALL)
###############################################################################
  # get some handy metrics from the node exporter (all nodes)
  - job_name: "node"
    static_configs:
      - targets:
        - "{{ (ds "tailscale").Self.HostName }}:9100"
        labels:
            env: prod
      ### PROD ###############
      - targets:
{{- range $hostDetail := (ds "tailscale").Peer }}
{{- if and (coll.Has $hostDetail "Tags") (coll.Has $hostDetail.Tags "tag:env-prod") }}
        - "{{ $hostDetail.HostName }}:9100"
{{- end }}
{{- end }}
        labels:
            env: prod
      ### DEV ###############
      - targets:
{{- range $hostDetail := (ds "tailscale").Peer }}
{{- if and (coll.Has $hostDetail "Tags") (coll.Has $hostDetail.Tags "tag:env-dev") }}
        - "{{ $hostDetail.HostName }}:9100"
{{- end }}
{{- end }}
        labels:
            env: dev
        
###############################################################################
# NGINX
###############################################################################
  # Scrape nginx exporter and nginxlog exporter for anything running nginx,
  # like mastodon-web or edge-cdn
  - job_name: "nginx"
    static_configs:
      ### PROD ###############
      - targets:
{{- range $hostDetail := (ds "tailscale").Peer }}
{{- if and (coll.Has $hostDetail "Tags") (coll.Has $hostDetail.Tags "tag:env-prod") }}
{{- if or (coll.Has $hostDetail.Tags "tag:role-mastodon-web") (coll.Has $hostDetail.Tags "tag:role-edge-cdn") (coll.Has $hostDetail.Tags "tag:role-mastodon-streaming") }}
        - "{{ $hostDetail.HostName }}:4040" # nginxlog
        - "{{ $hostDetail.HostName }}:9113"
{{- end }}
{{- end }}
{{- end }}
        labels:
            env: prod
      ### DEV ###############
      - targets:
{{- range $hostDetail := (ds "tailscale").Peer }}
{{- if and (coll.Has $hostDetail "Tags") (coll.Has $hostDetail.Tags "tag:env-dev") }}
{{- if or (coll.Has $hostDetail.Tags "tag:role-mastodon-web") (coll.Has $hostDetail.Tags "tag:role-edge-cdn") (coll.Has $hostDetail.Tags "tag:role-mastodon-streaming") }}
        - "{{ $hostDetail.HostName }}:4040" # nginxlog
        - "{{ $hostDetail.HostName }}:9113"
{{- end }}
{{- end }}
{{- end }}
        labels:
            env: dev

###############################################################################
# ELASTICSEARCH STATSD
###############################################################################
  # statsd has been deprecated in mastodon-sidekiq, so we're only scraping this from
  # the localhost (our mastodon stats exporter). also include elasticsearch nodes.
  - job_name: "statsd"
    static_configs:
      - targets: ["localhost:9876"]  # mastodon_api for hachyderm.io
        labels:
            env: prod
      ### PROD ###############
      - targets:
{{- range $hostDetail := (ds "tailscale").Peer }}
{{- if and (coll.Has $hostDetail "Tags") (coll.Has $hostDetail.Tags "tag:env-prod")  }}
{{- if or (coll.Has $hostDetail.Tags "tag:role-elasticsearch") }}
        - "{{ $hostDetail.HostName }}:9102"
{{- end }}
{{- end }}
{{- end }}
        labels:
            env: prod
      ### DEV ###############
      - targets:
{{- range $hostDetail := (ds "tailscale").Peer }}
{{- if and (coll.Has $hostDetail "Tags") (coll.Has $hostDetail.Tags "tag:env-dev")  }}
{{- if or (coll.Has $hostDetail.Tags "tag:role-elasticsearch") }}
        - "{{ $hostDetail.HostName }}:9102"
{{- end }}
{{- end }}
{{- end }}
        labels:
            env: dev
    relabel_configs:
      - source_labels: [__param_target]
        target_label: instance

###############################################################################
# POSTGRESQL
###############################################################################
  # postgresql exporter
  - job_name: "postgresql"
    static_configs:
      ### PROD ###############
      - targets:
{{- range $hostDetail := (ds "tailscale").Peer }}
{{- if and (coll.Has $hostDetail "Tags") (coll.Has $hostDetail.Tags "tag:env-prod") }}
{{- if or (coll.Has $hostDetail.Tags "tag:role-postgres-primary") (coll.Has $hostDetail.Tags "tag:role-postgres-backup")  }}
        - "{{ $hostDetail.HostName }}:9187"
        - "{{ $hostDetail.HostName }}:9930" # pgcat
{{- end }}
{{- end }}
{{- end }}
        labels:
            env: prod
      ### DEV ###############
      - targets:
{{- range $hostDetail := (ds "tailscale").Peer }}
{{- if and (coll.Has $hostDetail "Tags") (coll.Has $hostDetail.Tags "tag:env-dev") }}
{{- if or (coll.Has $hostDetail.Tags "tag:role-postgres-primary") (coll.Has $hostDetail.Tags "tag:role-postgres-backup")  }}
        - "{{ $hostDetail.HostName }}:9187"
        - "{{ $hostDetail.HostName }}:9930" # pgcat
{{- end }}
{{- end }}
{{- end }}
        labels:
            env: dev

###############################################################################
# REDIS
###############################################################################
  - job_name: "redis"
    static_configs:
      ### PROD ###############
      - targets:
{{- range $hostDetail := (ds "tailscale").Peer }}
{{- if and (coll.Has $hostDetail "Tags") (coll.Has $hostDetail.Tags "tag:env-prod") }}
{{- if or (coll.Has $hostDetail.Tags "tag:role-redis") }}
        - "{{ $hostDetail.HostName }}:9187"
{{- end }}
{{- end }}
{{- end }}
        labels:
            env: prod
      ### DEV ###############
      - targets:
{{- range $hostDetail := (ds "tailscale").Peer }}
{{- if and (coll.Has $hostDetail "Tags") (coll.Has $hostDetail.Tags "tag:env-dev") }}
{{- if or (coll.Has $hostDetail.Tags "tag:role-redis") }}
        - "{{ $hostDetail.HostName }}:9187"
{{- end }}
{{- end }}
{{- end }}
        labels:
            env: dev

###############################################################################
# MASTODON STREAMING
###############################################################################
  - job_name: "streaming"
    static_configs:
      - targets: ["prod-mastodon-streaming01:4000", "prod-mastodon-streaming01:4001", "prod-mastodon-streaming01:4002"]
        labels:
          env: "prod"
      - targets: ["dev-mastodon01:4000"]
        labels:
          env: "dev"
    metric_relabel_configs:
      - source_labels: [ __name__ ]
        target_label: __name__
        regex: '(.*)'
        action: replace
        replacement: mastodon_streaming_${1}

###############################################################################
# SIDEKIQ
###############################################################################
  - job_name: "sidekiq"
    static_configs:
      ### PROD ###############
      - targets:
{{- range $hostDetail := (ds "tailscale").Peer }}
{{- if and (coll.Has $hostDetail "Tags") (coll.Has $hostDetail.Tags "tag:env-prod") }}
{{- if or (coll.Has $hostDetail.Tags "tag:role-mastodon-sidekiq") }}
        - "{{ $hostDetail.HostName }}:9187"
{{- end }}
{{- end }}
{{- end }}
        labels:
            env: prod
      ### DEV ###############
      - targets:
{{- range $hostDetail := (ds "tailscale").Peer }}
{{- if and (coll.Has $hostDetail "Tags") (coll.Has $hostDetail.Tags "tag:env-dev") }}
{{- if or (coll.Has $hostDetail.Tags "tag:role-mastodon-sidekiq") }}
        - "{{ $hostDetail.HostName }}:9187"
{{- end }}
{{- end }}
{{- end }}
        labels:
            env: dev
